name: coin_market_cap_api
description: Dart Client for Coin Market Cap API.
version: 1.0.0+1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.13.3
  json_annotation: ^4.0.0
  flutter:
    sdk: flutter
  path_provider: ^2.0.2

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^4.0.0
  flutter_test:
    sdk: flutter